[project]
name = "dir-trigger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "watchdog>=6.0.0",
]

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["E", "W", "N", "PL"]
preview = true
